export const SIGNUP_USER = "SIGNUP_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGGEDIN_USER = "LOGGEDIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_EXERCISES = 'GET_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const GET_EXERCISE_INFO = 'GET_EXERCISE_INFO';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
