export const SUCCESS_SIGNUP = "SUCCESS_SIGNUP";
export const FAILURE_SIGNUP = "FAILURE_SIGNUP";
export const SUCCESS_LOGIN = "SUCCESS_LOGIN";
export const FAILURE_LOGIN = "FAILURE_LOGIN";
export const AUTH_USER = "AUTH_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const GET_EXERCISES = 'GET_EXERCISES';
export const ADD_EXERCISE = 'ADD_EXERCISE';
export const EDIT_EXERCISE = 'EDIT_EXERCISE';
export const GET_EXERCISE_INFO = 'GET_EXERCISE_INFO';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const HANDLE_CREATE_EX_FORM = 'HANDLE_CREATE_EX_FORM';
export const HANDLE_RENAME_EX_FORM = 'HANDLE_RENAME_EX_FORM';

export const GET_ALL_METRICS = 'GET_ALL_METRICS';
export const CREATE_METRIC = 'CREATE_METRIC';
export const HANDLE_CREATE_METRIC_FORM = 'HANDLE_CREATE_METRIC_FORM';
export const HANDLE_EDIT_METRIC_FORM = 'HANDLE_EDIT_METRIC_FORM';
export const GET_METRIC_INFO = 'GET_METRIC_INFO';
export const EDIT_METRIC = 'EDIT_METRIC';
export const DELETE_METRIC = 'DELETE_METRIC';

export const ADD_RESULT = 'ADD_RESULT';
export const HANDLE_RESULTS_FORM = 'HANDLE_RESULTS_FORM';

export const ADD_MEASURE = 'ADD_MEASURE';
export const HANDLE_MEASURE_FORM = 'HANDLE_MEASURE_FORM'; 

export const GET_ALL_WORKOUTS = 'GET_ALL_WORKOUTS';
export const HANDLE_CREATE_WORKOUT_FORM = 'HANDLE_CREATE_WORKOUT_FORM';
export const CREATE_WORKOUT = 'CREATE_WORKOUT';

export const SAVE_INTERVAL = 'SAVE_INTERVAL';
export const COUNT_TIME = 'COUNT_TIME';
export const STOP_INTERVAL = 'STOP_INTERVAL';
export const RESET_TIME = 'RESET_TIME';
export const SET_TIMER_READY = 'SET_TIMER_READY';
export const SET_END_SESSION = 'SET_END_SESSION';

export const SET_AMRAP_TIME = 'SET_AMRAP_TIME';
export const ADD_AMRAP_SET = 'ADD_AMRAP_SET';
export const REMOVE_AMRAP_SET = 'REMOVE_AMRAP_SET';
export const EDIT_AMRAP_SET = 'EDIT_AMRAP_SET';

export const SET_ALERT = 'SET_ALERT';